version: "3"

services:
  redis:
    image: redis

  master:
    image: ${FAABRIC_CLI_IMAGE}
    volumes:
      - ${PROJ_ROOT}:/code/faabric
      - ${FAABRIC_LOCAL_BUILD_DIR}:${FAABRIC_BUILD_MOUNT}
      - ${PROJ_ROOT}/dist-test/build:/build/faabric-copy
    working_dir: /code/faabric
    stdin_open: true
    tty: true
    environment:
      - LOG_LEVEL=debug
      - REDIS_STATE_HOST=redis
      - REDIS_QUEUE_HOST=redis
    depends_on:
      - redis
      - worker

  worker:
    image: ${FAABRIC_CLI_IMAGE}
    volumes:
      - ${PROJ_ROOT}:/code/faabric
      - ${FAABRIC_LOCAL_BUILD_DIR}:${FAABRIC_BUILD_MOUNT}
      - ${PROJ_ROOT}/dist-test/build:/build/faabric-copy
    working_dir: /code/faabric
    environment:
      - LOG_LEVEL=debug
      - REDIS_STATE_HOST=redis
      - REDIS_QUEUE_HOST=redis
    depends_on:
      - redis
    command: /build/faabric/static/bin/faabric_dist_test_server
