name: Tests

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      HOST_TYPE: ci
      REDIS_QUEUE_HOST: redis
      REDIS_STATE_HOST: redis
    container:
      image: faasm/faabric-cli:0.0.14
    defaults:
      run:
        working-directory: /code/faabric
    services:
      redis:
        image: redis
    steps:
      # --- Code update ---
      - name: "Fetch ref"
        run: git fetch origin ${GITHUB_REF}:ci-branch
      - name: "Check out branch"
        run: git checkout --force ci-branch
      # --- Formatting checks ---
      - name: "Python formatting check"
        run: ./bin/check_black.sh
      - name: "Run C/C++ formatting"
        run: ./bin/run_clang_format.sh 
      - name: "Check C/C++ formatting changes"
        run: git diff --exit-code
      # --- Set-up ---
      - name: "Ping redis"
        run: redis-cli -h redis ping
      # --- Build ---
      - name: "Run cmake static"
        run: inv dev.cmake
      - name: "Run cmake shared"
        run: inv dev.cmake --shared
      - name: "Build tests"
        run: inv dev.cc faabric_tests
      - name: "Build Faabric static library"
        run: inv dev.cc faabric
      - name: "Build Faabric shared library"
        run: inv dev.cc faabric --shared
      - name: "Install Faabric static library"
        run: inv dev.install faabric
      - name: "Install Faabric shared library"
        run: inv dev.install faabric --shared
      - name: "Build examples"
        run: inv examples
      # --- Tests ---
      - name: "Run tests"
        run: ./bin/faabric_tests
        working-directory: /build/faabric/static
